version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
    environment:
      DOCS_PATH: "docs"
      GIT_USER: "icyleaf"
      GIT_EMAIL: "icyleaf.cn@gmail.com"
      GIT_REPO: "git@github.com:icyleaf/popcorn.git"
      GH_REF: "https://github.com/icyleaf/popcorn"
    branches:
      ignore:
        - gh-pages
    working_directory: ~/popcorn
    steps:
      - checkout
      - run:
          name: "Crystal Version"
          command: crystal version
      - run:
          name: "Specs"
          command: crystal spec